excerpt_separator: ""
pygments: true
markdown: kramdown
title: Tuna knows
tagline: Sniffing out insights from data
description: Where I attempt as far as possible to stay on topic about Social Intelligence, technology and stuff I am generally daydreaming about.
paginate: 5
